# Generated by Django 4.2.1 on 2023-09-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_order_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="item",
        ),
    ]
